# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jRwM19bcvrXt5Rk85w7uZudpqAnj8UNq
"""

# Import required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Creating dataset based on real-world trends (India)

data = {
    "Year": list(range(2015, 2024)),

    # Aspirations proxies
    "Enrollment": [25, 26, 27, 28, 29, 30, 31, 32, 33],  # Higher education %
    "Internet": [27, 30, 34, 38, 41, 45, 47, 50, 55],    # % population
    "Students_Abroad": [450000, 500000, 550000, 600000, 650000, 700000, 750000, 800000, 850000],

    # Opportunities proxies
    "Jobs_Index": [40, 42, 43, 44, 45, 44, 46, 47, 48],
    "Learning_Index": [30, 31, 32, 33, 34, 34, 35, 36, 37],
    "RnD": [0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7]
}

df = pd.DataFrame(data)
df

"""Normalizing Variables"""

# Normalize (0–1 scale)

df["Enroll_norm"] = df["Enrollment"] / df["Enrollment"].max()
df["Internet_norm"] = df["Internet"] / df["Internet"].max()
df["Abroad_norm"] = df["Students_Abroad"] / df["Students_Abroad"].max()

df["Jobs_norm"] = df["Jobs_Index"] / df["Jobs_Index"].max()
df["Learning_norm"] = df["Learning_Index"] / df["Learning_Index"].max()
df["RnD_norm"] = df["RnD"] / df["RnD"].max()

df.head()

# Aspirations Score
df["Aspirations"] = (
    df["Enroll_norm"] +
    df["Internet_norm"] +
    df["Abroad_norm"]
) / 3

# Opportunities Score
df["Opportunities"] = (
    df["Jobs_norm"] +
    df["Learning_norm"] +
    df["RnD_norm"]
) / 3

df[["Year", "Aspirations", "Opportunities"]]

# AOMI = Aspirations - Opportunities

df["AOMI"] = df["Aspirations"] - df["Opportunities"]

df[["Year", "AOMI"]]

plt.figure()

plt.plot(df["Year"], df["Aspirations"], label="Aspirations")
plt.plot(df["Year"], df["Opportunities"], label="Opportunities")
plt.plot(df["Year"], df["AOMI"], label="Mismatch (AOMI)")

plt.title("India’s Aspiration–Opportunity Mismatch Index")
plt.xlabel("Year")
plt.ylabel("Normalized Value")

plt.legend()
plt.show()

# Find peak mismatch

max_year = df.loc[df["AOMI"].idxmax(), "Year"]
max_value = df["AOMI"].max()

print(f"Highest mismatch occurs in {max_year} with value {max_value:.3f}")

# Simulate improvement in opportunities

df["Improved_Opportunities"] = df["Opportunities"] * 1.2

df["New_AOMI"] = df["Aspirations"] - df["Improved_Opportunities"]

# Plot comparison
plt.figure()

plt.plot(df["Year"], df["AOMI"], label="Original AOMI")
plt.plot(df["Year"], df["New_AOMI"], label="After Policy Improvement")

plt.title("Impact of Improving Opportunities")
plt.xlabel("Year")
plt.ylabel("Mismatch Index")

plt.legend()
plt.show()

"""**REGRESSION** **ANALYSIS**"""

import statsmodels.api as sm

# Dependent variable
Y = df["AOMI"]

# Independent variables
X = df[["Aspirations", "Opportunities"]]

# Add constant (important)
X = sm.add_constant(X)

model = sm.OLS(Y, X).fit()

print(model.summary())

"""🔹 Coefficients
1.  Aspirations → positive (should increase mismatch)
2.  Opportunities → negative (reduces mismatch)


🔹 p-values
1.   < 0.05 → statistically significant
2.   0.05 → weak evidence


🔹 R²
Measures how well model explains mismatch


The regression results indicate that aspirations have a positive and significant impact on mismatch, while opportunities reduce it. This supports the hypothesis that rising educational and exposure-driven aspirations are outpacing the economy’s ability to generate adequate opportunities.
"""

# Create interaction term
df["Interaction"] = df["Aspirations"] * df["Opportunities"]

X2 = df[["Aspirations", "Opportunities", "Interaction"]]
X2 = sm.add_constant(X2)

model2 = sm.OLS(Y, X2).fit()

print(model2.summary())

"""The interaction term captures how the relationship between aspirations and mismatch changes with opportunity levels, providing deeper insight into structural imbalance."""

# Predicted values
df["Predicted_AOMI"] = model.predict(X)

plt.figure()
plt.plot(df["Year"], df["AOMI"], label="Actual")
plt.plot(df["Year"], df["Predicted_AOMI"], label="Predicted")

plt.legend()
plt.title("Regression Fit: Actual vs Predicted AOMI")
plt.show()